name: Build and Export Docker Images

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  export-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull images
        run: |
          docker pull mysql:8.0
          docker pull elabftw/elabftw:latest

      - name: Save and compress
        run: |
          docker save mysql:8.0 | gzip > mysql-8.0.tar.gz
          docker save elabftw/elabftw:latest | gzip > elabftw-latest.tar.gz

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: |
            mysql-8.0.tar.gz
            elabftw-latest.tar.gz
